### ISSUE TITLE
bug v 0.0.17

### ISSUE THREAD

**Issue by studiozocaro** [Enough-Software/enough_mail#48]
i have this error after update to v0.0.17
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'toLowerCase' was called on null.
Receiver: null
Tried calling: toLowerCase()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ContentTypeHeader.setParameter (package:enough_mail/mime_message.dart:804:17)
#2      FetchParser._parseBody (package:enough_mail/src/imap/fetch_parser.dart:353:16)
#3      FetchParser._parseBodyStructure (package:enough_mail/src/imap/fetch_parser.dart:361:5)
#4      FetchParser._parseFetch (package:enough_mail/src/imap/fetch_parser.dart:77:11)
#5      FetchParser.parseUntagged (package:enough_mail/src/imap/fetch_parser.dart:32:11)
#6      CommandTask.parseUntaggedResponse (package:enough_mail/src/imap/command.dart:73:21)
#7      ImapClient.onUntaggedResponse (package:enough_mail/imap/imap_client.dart:1051:31)
#8      ImapClient.onServerResponse (package:enough_mail/imap/imap_client.dart:1019:7)
#9      ImapResponseReader._checkResponse (package:enough_mail/src/ima<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'toLowerCase' was called on null.
Receiver: null
Tried calling: toLowerCase()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ContentTypeHeader.setParameter (package:enough_mail/mime_message.dart:804:17)
#2      FetchParser._parseBody (package:enough_mail/src/imap/fetch_parser.dart:323:35)
#3      FetchParser._parseBodyStructure (package:enough_mail/src/imap/fetch_parser.dart:361:5)
#4      FetchParser._parseFetch (package:enough_mail/src/imap/fetch_parser.dart:77:11)
#5      FetchParser.parseUntagged (package:enough_mail/src/imap/fetch_parser.dart:32:11)
#6      CommandTask.parseUntaggedResponse (package:enough_mail/src/imap/command.dart:73:21)
#7      ImapClient.onUntaggedResponse (package:enough_mail/imap/imap_client.dart:1051:31)
#8      ImapClient.onServerResponse (package:enough_mail/imap/imap_client.dart:1019:7)
#9      ImapResponseReader._checkResponse (package:enough_mail/src/ima<…>

**Comment by ali7234** [comment]
> 
> 
> i have this error after update to v0.0.17
> [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'toLowerCase' was called on null.
> Receiver: null
> Tried calling: toLowerCase()
> #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
> #1 ContentTypeHeader.setParameter (package:enough_mail/mime_message.dart:804:17)
> #2 FetchParser._parseBody (package:enough_mail/src/imap/fetch_parser.dart:353:16)
> #3 FetchParser._parseBodyStructure (package:enough_mail/src/imap/fetch_parser.dart:361:5)
> #4 FetchParser._parseFetch (package:enough_mail/src/imap/fetch_parser.dart:77:11)
> #5 FetchParser.parseUntagged (package:enough_mail/src/imap/fetch_parser.dart:32:11)
> #6 CommandTask.parseUntaggedResponse (package:enough_mail/src/imap/command.dart:73:21)
> #7 ImapClient.onUntaggedResponse (package:enough_mail/imap/imap_client.dart:1051:31)
> #8 ImapClient.onServerResponse (package:enough_mail/imap/imap_client.dart:1019:7)
> #9 ImapResponseReader._checkResponse (package:enough_mail/src/ima<…>
> [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'toLowerCase' was called on null.
> Receiver: null
> Tried calling: toLowerCase()
> #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
> #1 ContentTypeHeader.setParameter (package:enough_mail/mime_message.dart:804:17)
> #2 FetchParser._parseBody (package:enough_mail/src/imap/fetch_parser.dart:323:35)
> #3 FetchParser._parseBodyStructure (package:enough_mail/src/imap/fetch_parser.dart:361:5)
> #4 FetchParser._parseFetch (package:enough_mail/src/imap/fetch_parser.dart:77:11)
> #5 FetchParser.parseUntagged (package:enough_mail/src/imap/fetch_parser.dart:32:11)
> #6 CommandTask.parseUntaggedResponse (package:enough_mail/src/imap/command.dart:73:21)
> #7 ImapClient.onUntaggedResponse (package:enough_mail/imap/imap_client.dart:1051:31)
> #8 ImapClient.onServerResponse (package:enough_mail/imap/imap_client.dart:1019:7)
> #9 ImapResponseReader._checkResponse (package:enough_mail/src/ima<…>

Also, face the same issue.

**Comment by robert-virkus** [comment]
Thanks, can you post the `* FETCH (BODYSTRUCTURE)` IMAP response details?

**Comment by studiozocaro** [comment]
flutter: S: * 2014 FETCH (FLAGS (\Seen) BODYSTRUCTURE ((("TEXT" "PLAIN" ("CHARSET" "UTF-8") NIL NIL "7BIT" 2 1 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "UTF-8") NIL NIL "7BIT" 24 1 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "00000000000005d37e05a528d9c3") NIL NIL)("APPLICATION" "PDF" ("NAME" "gdpr infomedica informativa clienti.pdf") "<171f5fa0424e36cb441>" NIL "BASE64" 238268 NIL ("ATTACHMENT" ("FILENAME" "gdpr infomedica informativa clienti.pdf")) NIL) "MIXED" ("BOUNDARY" "00000000000005d38005a528d9c5") NIL NIL) BODY[HEADER] {337}
MIME-Version: 1.0

Date: Fri, 8 May 2020 22:29:00 +0200

Message-ID: <CAMLzNq8XgApDFiunF19yTBUzXtc-FSNApsW19Y1Q9HPdDshEUg@mail.gmail.com>

Subject: gdpr infomedica informativa clienti.pdf

From: Flavio Zocaro <studiozocaro@gmail.com>

To: studiozocaro@gmail.com

Content-Type: multipart/mixed; boundary="00000000000005d38005a528d9c5"




)
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'toLowerCase' was called on null.
Receiver: null
Tried calling: toLowerCase()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ContentTypeHeader.setParameter (package:enough_mail/mime_message.dart:804:17)
#2      FetchParser._parseBody (package:enough_mail/src/imap/fetch_parser.dart:357:16)
#3      FetchParser._parseBodyStructure (package:enough_mail/src/imap/fetch_parser.dart:365:5)
#4      FetchParser._parseFetch (package:enough_mail/src/imap/fetch_parser.dart:77:11)
#5      FetchParser.parseUntagged (package:enough_mail/src/imap/fetch_parser.dart:32:11)
#6      CommandTask.parseUntaggedResponse (package:enough_mail/src/imap/command.dart:73:21)
#7      ImapClient.onUntaggedResponse (package:enough_mail/imap/imap_client.dart:1051:31)
#8      ImapClient.onServerResponse (package:enough_mail/imap/imap_client.dart:1019:7)

#9      ImapResponseReader._checkResponse (package:enough_mail/src/ima<…>
flutter: S: * 2014 FETCH (FLAGS (\Seen) BODYSTRUCTURE ((("TEXT" "PLAIN" ("CHARSET" "UTF-8") NIL NIL "7BIT" 2 1 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "UTF-8") NIL NIL "7BIT" 24 1 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "00000000000005d37e05a528d9c3") NIL NIL)("APPLICATION" "PDF" ("NAME" "gdpr infomedica informativa clienti.pdf") "<171f5fa0424e36cb441>" NIL "BASE64" 238268 NIL ("ATTACHMENT" ("FILENAME" "gdpr infomedica informativa clienti.pdf")) NIL) "MIXED" ("BOUNDARY" "00000000000005d38005a528d9c5") NIL NIL) BODY[HEADER] {337}
MIME-Version: 1.0

Date: Fri, 8 May 2020 22:29:00 +0200

Message-ID: <CAMLzNq8XgApDFiunF19yTBUzXtc-FSNApsW19Y1Q9HPdDshEUg@mail.gmail.com>

Subject: gdpr infomedica informativa clienti.pdf

From: Flavio Zocaro <studiozocaro@gmail.com>

To: studiozocaro@gmail.com

Content-Type: multipart/mixed; boundary="00000000000005d38005a528d9c5"




)
* 2015 FETCH (FLAGS (\Seen) BODYSTRUCTURE ("TEXT" "HTML" ("CHARSET" "UTF-8") NIL NIL "8BIT" 13045 261 NIL NIL NIL) BODY[HEADER] {3249}
De<…>
flutter: ERROR: no task found for command [2014]

**Comment by studiozocaro** [comment]
flutter: C: a4 FETCH 2014 BODYSTRUCTURE
flutter: S: * 2014 FETCH (BODYSTRUCTURE ((("TEXT" "PLAIN" ("CHARSET" "UTF-8") NIL NIL "7BIT" 2 1 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "UTF-8") NIL NIL "7BIT" 24 1 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "00000000000005d37e05a528d9c3") NIL NIL)("APPLICATION" "PDF" ("NAME" "gdpr infomedica informativa clienti.pdf") "<171f5fa0424e36cb441>" NIL "BASE64" 238268 NIL ("ATTACHMENT" ("FILENAME" "gdpr infomedica informativa clienti.pdf")) NIL) "MIXED" ("BOUNDARY" "00000000000005d38005a528d9c5") NIL NIL))
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'toLowerCase' was called on null.
Receiver: null
Tried calling: toLowerCase()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ContentTypeHeader.setParameter (package:enough_mail/mime_message.dart:804:17)
#2      FetchParser._parseBody (package:enough_mail/src/imap/fetch_parser.dart:357:16)
#3      FetchParser._parseBodyStructure (package:enough_mail/src/imap/fetch_parser.dart:365:5)
#4      FetchParser._parseFetch (package:enough_mail/src/imap/fetch_parser.dart:77:11)
#5      FetchParser.parseUntagged (package:enough_mail/src/imap/fetch_parser.dart:32:11)
#6      CommandTask.parseUntaggedResponse (package:enough_mail/src/imap/command.dart:73:21)
#7      ImapClient.onUntaggedResponse (package:enough_mail/imap/imap_client.dart:1051:31)
#8      ImapClient.onServerResponse (package:enough_mail/imap/imap_client.dart:1019:7)

#9      ImapResponseReader.onData (package:enough_mail/src/imap/imap_r<…>
flutter: S: a4 OK Success

**Comment by robert-virkus** [comment]
Thanks, I can replicate the problem. Will update once it's fixed.

**Comment by robert-virkus** [comment]
Please upgrade to v0.0.18, this should fix the problems. Please note the API changes when accessing the MimeMessage.body element, this is now close to the normal MimeMessage API. Compare https://pub.dev/documentation/enough_mail/latest/mime_message/BodyPart-class.html for details.

When the problems are fixed for you, please close this bug.

**Comment by studiozocaro** [comment]
how to get BODYSTRUCTURE?

**Comment by studiozocaro** [comment]
ok, is body when BODYSTRUCTURE

**Comment by robert-virkus** [comment]
Yes, `Mime Message.body` contains the result for both BODY and BODYSTRUCTURE fetch calls. Please close this issue of it works for you now.
